### ISSUE TITLE
docker-compose is deprecated

### ISSUE THREAD

**Issue by physikerwelt** [ER-FIZKarlsruhe/fiz-oai-docker#1]
> From July 2023 Compose V1 stopped receiving updates. It’s also no longer available in new releases of Docker Desktop.

https://docs.docker.com/compose/migrate/

I think it is sufficient to replace the - with a space in the readme

https://github.com/ER-FIZKarlsruhe/fiz-oai-docker/blob/64b7ead2e2ee5f578025e136e5423b4ecc468bb3/README.md?plain=1#L13C24-L13C25

**Comment by stefanbozic** [comment]
README has been adapted.
