### ISSUE TITLE
docker.dev.fiz-karlsruhe.de/cassandra-backup:1 not found

### ISSUE THREAD

**Issue by physikerwelt** [ER-FIZKarlsruhe/fiz-oai-docker#3]
From

https://github.com/ER-FIZKarlsruhe/fiz-oai-docker/blob/64b7ead2e2ee5f578025e136e5423b4ecc468bb3/docker-compose.yml#L32C1-L32C58

leads to the following error message
> Pulling cassandra-backup (docker.dev.fiz-karlsruhe.de/cassandra-backup:1)...
manifest for docker.dev.fiz-karlsruhe.de/cassandra-backup:1 not found: manifest unknown: The named manifest is not known to the registry.

**Comment by physikerwelt** [comment]
It was available before with this hash f08cfcfaf1b3d53087ea9f57fdf79d7861fecbc2aaef715f17225521b879e142

**Comment by physikerwelt** [comment]
The new version does not crash, however it also does not seem to work out of the box
```
root@cassandra-backup:/logs# cat cron.log 
2023-10-12-02-00-01: Running Cassandra Check for Incremental Backup
running
2023-10-12-02-30-01: Running Cassandra Backup -h cassandra-oai -p 7199 -u fizoaibackend
CQLSH_HOST is cassandra-oai
CASSANDRA_KEYSPACES is escidocng fizoaibackend system_auth system_traces system_distributed system system_schema
nodetool: Keyspace [escidocng] does not exist.
See 'nodetool help' or 'nodetool help <command>'.
mail: Null message body; hope that's ok

**Comment by stefanbozic** [comment]
Image version has been changed to docker.dev.fiz-karlsruhe.de/cassandra-backup:5.2
